config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  devise_for :employees
  
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions'}, :skip => :registration

  devise_scope :admin do
    authenticated :admin do
      namespace :admins do
        get 'dashboard/index', as: :root
      end
    end
  end

  namespace :admins do
    resources :kudos
    resources :employees
    resources :company_values
    resources :rewards
    resources :orders
  end

  resources :rewards
  resources :orders
  resources :kudos

  root to: "kudos#index"
end

app/models/company_value.rb
class CompanyValue < ApplicationRecord
  has_many :kudos, dependent: :destroy

  validates :title, presence: true, uniqueness: true, allow_nil: false
end

app/controllers/admins/company_values_controller.rb
module Admins
  class CompanyValuesController < AdminController
    def index
      @company_values = CompanyValue.all.order(:created_at)
    end

    def new
      @company_value = CompanyValue.new
    end

    def edit
      company_value
    end

    def create
      @company_value = CompanyValue.new(company_value_params)

      if @company_value.save
        redirect_to admins_company_values_path, notice: 'Company value was successfully created.'
      else
        render :new
      end
    end

    def update
      company_value
      if @company_value.update(company_value_params)
        redirect_to admins_company_values_path, notice: 'Company value was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      company_value
      @company_value.destroy
      redirect_to admins_company_values_path, notice: 'Company value was successfully destroyed.'
    end

    private

    def company_value
      @company_value = CompanyValue.find(params[:id])
    end

    def company_value_params
      params.require(:company_value).permit(:title)
    end
  end
end

app/views/admins/company_values/_form.html.erb
<%= form_with model: [:admins, @company_value] do |form| %>

  <div class="col-md-6">
    <div class="form-group">
      <%= "Id: #{@company_value.id}" %>
    </div>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= "Creation time: #{@company_value.created_at}" %>
    </div>

    <div class="form-group">
      <%= "Update time: #{@company_value.updated_at}" %>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-primary" %>
    </div>
    <br>
  </div>

<% end %>

app/views/admins/company_values/edit.html.erb
<h1>Editing Company value</h1>

<%= render 'form', company_value: @company_value %>

<%= link_to 'Back', admins_company_values_path %>

app/views/admins/company_values/index.html.erb
<h1>Company value</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Creation time</th>
      <th>Update time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_values.each do |company_value| %>
      <tr>
        <td><%= company_value.id %></td>
        <td><%= company_value.title %></td>
        <td><%= company_value.created_at%></td>
        <td><%= company_value.updated_at%></td>
        <td><%= link_to 'Edit', edit_admins_company_value_path(company_value) %></td>
        <td><%= link_to 'Destroy', admins_company_value_path(company_value), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Company value', new_admins_company_value_path %> |
<%= link_to 'Back', admins_root_path %>

app/views/admins/company_values/new.html.erb
<h1>New Company Value</h1>

<%= render 'form', company_value: @company_value %>

<%= link_to 'Back', admins_company_values_path %>