config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  devise_for :employees
  
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions'}, :skip => :registration

  devise_scope :admin do
    authenticated :admin do
      namespace :admins do
        get 'dashboard/index', as: :root
      end
    end
  end

  namespace :admins do
    resources :kudos
    resources :employees
    resources :company_values
    resources :rewards
    resources :orders
  end

  resources :rewards
  resources :orders
  resources :kudos

  root to: "kudos#index"
end

app/models/reward.rb
class Reward < ApplicationRecord
  validates :title, :description, presence: true

  validates :price, numericality: { greater_than_or_equal_to: 1 }, presence: true

  has_many :orders, dependent: :destroy
end

app/controllers/admins/rewards_controller.rb
module Admins
  class RewardsController < AdminController
    def index
      @rewards = Reward.all.order(:created_at)
    end

    def show
      reward
    end

    def new
      @reward = Reward.new
    end

    def edit
      reward
    end

    # def create
    #   @reward = Reward.new(reward_params)
    #   if @reward.save
    #     redirect_to admins_rewards_path, notice: 'Reward was successfully created.'
    #   else
    #     render :new
    #   end
    # end

    # def update
    #   reward
    #   if @reward.update!(reward_params)
    #     redirect_to admins_rewards_path, notice: 'Reward was successfully updated.'
    #   else
    #     render :edit
    #   end
    # end

    # def destroy
    #   reward
    #   @reward.destroy
    #   redirect_to admins_rewards_path, notice: 'Reward was successfully destroyed.'
    # end

    def create
      @reward = Reward.new(reward_params)
      ::Rewards::CreateService.new.call(reward: @reward)
      flash[:notice] = 'Reward was successfully created.'
      redirect_to admins_rewards_path
    rescue ActiveRecord::RecordInvalid => e
      flash[:error] = e.to_s
      render :new
    end

    def update
      ::Rewards::UpdateService.new.call(reward: reward, **reward_params.to_unsafe_hash.symbolize_keys)
      flash[:notice] = 'Reward was successfully updated.'
      redirect_to admins_rewards_path
    rescue ActiveRecord::RecordInvalid => e
      flash[:error] = e.to_s
      render :edit
    end

    def destroy
      reward
      @reward.destroy
      redirect_to admins_rewards_path, notice: 'Reward was successfully destroyed.'
    end

    private

    def reward
      @reward = Reward.find(params[:id])
    end

    def reward_params
      params.require(:reward).permit(:title, :description, :price)
    end
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :authenticate_employee!

  def index
    @rewards = Reward.order(:created_at)
  end

  def show
    @reward = Reward.find(params[:id])
  end
end

app/views/admins/rewards/_form.html.erb
<%= form_with model: [:admins, @reward] do |form| %>

  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :price %>
      <%= form.number_field :price, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.submit class: "btn btn-primary" %>
    </div>
    <br>
  </div>
<% end %>

app/views/admins/rewards/index.html.erb
<h1>Rewards</h1>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Creation time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rewards.each do |reward| %>
      <tr>
        <td><%= reward.id %></td>
        <td><%= reward.title %></td>
        <td><%= reward.description %></td>
        <td><%= reward.price %></td>
        <td><%= reward.created_at.strftime("%F") %></td>
        <td><%= link_to 'Show', admins_reward_path(reward), class: "btn btn-dark" %></td>
        <td><%= link_to 'Edit', edit_admins_reward_path(reward), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', admins_reward_path(reward), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Reward', new_admins_reward_path, class: "btn btn-primary" %>

app/views/admins/rewards/show.html.erb
<p>
  <strong>Id:</strong>
  <%= @reward.id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @reward.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reward.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @reward.price%>
</p>

<p>
  <strong>Creation time:</strong>
  <%= @reward.created_at.strftime("%F")%>
</p>

<%= link_to 'Edit', edit_admins_reward_path(@reward), class: "btn btn-dark" %> &nbsp
<%= link_to 'Back', admins_rewards_path, class: "btn btn-secondary" %>