config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  devise_for :employees
  
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions'}, :skip => :registration

  devise_scope :admin do
    authenticated :admin do
      namespace :admins do
        get 'dashboard/index', as: :root
      end
    end
  end

  namespace :admins do
    resources :kudos
    resources :employees
    resources :company_values
    resources :rewards
    resources :orders
  end

  resources :rewards
  resources :orders
  resources :kudos

  root to: "kudos#index"
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee Recognition Platform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <h1><%= link_to 'Company', root_path, class: "btn btn-success btn-lg" %></h1>
      
      <div class="page-header">
        <% if flash[:notice].present? %>
          <div class="alert alert-success">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <% if flash[:error].present? %>
          <div class="alert alert-danger">
            <%= flash[:error] %>
          </div>
        <% end %>
        <% if flash[:alert].present? %>
          <div class="alert alert-danger">
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>

      <nav>
        <h4>Navigation</h4>
        <ul class ="nav">
          <% if admin_signed_in? %>
            <li><%= link_to 'Manage Kudos', admins_kudos_path, class: "btn btn-primary" %></li>&nbsp   
            <li><%= link_to 'Manage Employees', admins_employees_path, class: "btn btn-primary" %></li>&nbsp 
            <li><%= link_to 'Manage Company values', admins_company_values_path, class: "btn btn-primary" %></li>&nbsp
            <li><%= link_to 'Manage Rewards', admins_rewards_path, class: "btn btn-primary" %></li>&nbsp
            <li><%= link_to 'List of bought rewards', admins_orders_path, class: "btn btn-primary" %></li>&nbsp
            <li><%= link_to 'Sign out as Admin', destroy_admin_session_path, method: :delete, class: "btn btn-warning" %></li>&nbsp    
          <% end %>
        </ul>
      </nav>

    <%= yield %>
  
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee Recognition Platform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <h1><%= link_to 'Company', root_path, class:  "btn btn-success btn-lg" %></h1>
      
      <div class="page-header">
        <% if flash[:notice].present? %>
          <div class="alert alert-success">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <% if flash[:error].present? %>
          <div class="alert alert-danger">
            <%= flash[:error] %>
          </div>
        <% end %>
        <% if flash[:alert].present? %>
          <div class="alert alert-danger">
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>


      <nav>
        <h4>Navigation</h4>
        <ul class ="nav">
          <% if employee_signed_in? %>
            <button type="button" class="btn btn-info"><%= "Number of available kudos: #{current_employee.number_of_available_kudos}" %></button>&nbsp
            <button type="button" class="btn btn-info"><%= "Number of earned points: #{current_employee.earned_points}" %></button>&nbsp
            <%= link_to 'Kudos', root_path, class: "btn btn-primary"  %>&nbsp
            <%= link_to 'Rewards', rewards_path, class: "btn btn-primary"  %>&nbsp
            <%= link_to 'My orders', orders_path, class: "btn btn-primary"  %>&nbsp
            <%= link_to 'Sign out', destroy_employee_session_path, method: :delete, class: "btn btn-warning"  %>&nbsp
           <% elsif !admin_signed_in? %>
            <%= link_to "Sign in", new_employee_session_path, class: "btn btn-primary" %>&nbsp
            <%= link_to 'Sign up', new_employee_registration_path, class: "btn btn-primary" %>&nbsp
          <% end %>
          <% if admin_signed_in? %>
            <%= link_to 'Sign out as Admin', destroy_admin_session_path, method: :delete, class: "btn btn-warning" %>&nbsp    
          <% elsif !employee_signed_in? %>
            <%= link_to "Sign in as Admin", new_admin_session_path, class: "btn btn-primary" %>&nbsp
          <% end %>
        </ul>
      </nav>

    <%= yield %>
  
  </body>
</html>